export { default } from "./src/wallet-manager-solana.js";
export { default as WalletAccountReadOnlySolana } from "./src/wallet-account-read-only-solana.js";
export { default as WalletAccountSolana } from "./src/wallet-account-solana.js";
export type SolanaTransactionReceipt = ReturnType<import("@solana/rpc-api").SolanaRpcApi["getTransaction"]>;
export type FeeRates = import("@wdk/wallet").FeeRates;
export type KeyPair = import("@wdk/wallet").KeyPair;
export type TransactionResult = import("@wdk/wallet").TransactionResult;
export type TransferOptions = import("@wdk/wallet").TransferOptions;
export type TransferResult = import("@wdk/wallet").TransferResult;
export type SolanaTransaction = import("./src/wallet-account-solana.js").SolanaTransaction;
export type SolanaWalletConfig = import("./src/wallet-account-solana.js").SolanaWalletConfig;
