export { default } from "./src/wallet-manager-solana.js";
export { default as WalletAccountReadOnlySolana } from "./src/wallet-account-read-only-solana.js";
export { default as WalletAccountSolana } from "./src/wallet-account-solana.js";
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferOptions = import("@tetherto/wdk-wallet").TransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type Finality = import("@tetherto/wdk-wallet").Finality;
export type TransactionReceipt = import("@tetherto/wdk-wallet").TransactionReceipt;
export type WaitForTransactionTarget = import("@tetherto/wdk-wallet").WaitForTransactionTarget;
export type WaitForTransactionOptions = import("@tetherto/wdk-wallet").WaitForTransactionOptions;
export type SimpleSolanaTransaction = import("./src/wallet-account-read-only-solana.js").SimpleSolanaTransaction;
export type SolanaTransactionReceipt = import("./src/wallet-account-read-only-solana.js").SolanaTransactionReceipt;
export type SolanaTransactionDetails = import("./src/wallet-account-read-only-solana.js").SolanaTransactionDetails;
export type SolanaTransferOptions = import("./src/wallet-account-read-only-solana.js").SolanaTransferOptions;
export type SolanaTransferQuoteDetails = import("./src/wallet-account-read-only-solana.js").SolanaTransferQuoteDetails;
export type MintAccount = import("./src/wallet-account-read-only-solana.js").MintAccount;
export type TokenProgramAddress = import("./src/wallet-account-read-only-solana.js").TokenProgramAddress;
export type SolanaTransaction = import("./src/wallet-account-solana.js").SolanaTransaction;
export type SolanaWalletConfig = import("./src/wallet-account-solana.js").SolanaWalletConfig;
export { ConfidentialTransferNotSupportedError, FrozenTokenAccountError, NonTransferableTokenError, TransferHookNotSupportedError } from "./src/errors.js";
export { AssertionError, MaximumFeeExceededError, NoSuchElementError, ProviderRequiredError, TimeoutError, ValueError, WdkError } from "@tetherto/wdk-wallet";
